export const AYAH_FETCH_REQUEST = "AYAH_FETCH_REQUEST";
export const AYAH_FETCH_SUCCESS = "AYAH_FETCH_SUCCESS";
export const AYAH_FETCH_FAIL = "AYAH_FETCH_FAIL";

export const NEXT_AYAH_FETCH_REQUEST = "NEXT_AYAH_FETCH_REQUEST";
export const NEXT_AYAH_FETCH_SUCCESS = "NEXT_AYAH_FETCH_SUCCESS";
export const NEXT_AYAH_FETCH_FAIL = "NEXT_AYAH_FETCH_FAIL";

export const AYAH_SELECTION = "AYAH_SELECTION";

export const AYAH_NUMBER_CHANGE = "AYAH_NUMBER_CHANGE";

export const SHEIKH_CHANGE = "SHEIKH_CHANGE";

export const QUALITY_CHANGE = "QUALITY_CHANGE";
